### ISSUE TITLE
compile error in linux x86 gcc5.5 [12545]

### ISSUE THREAD

**Issue by QinChen686** [eProsima/Fast-DDS#2174]
/data/workspace/Fast-DDS/src/cpp/rtps/flowcontrol/FlowControllerFactory.cpp:24:87:   required from here
**/usr/include/c++/5/ext/new_allocator.h:120:4: error: use of deleted function ‘constexpr std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = const std::__cxx11::basic_string<char>; _T2 = std::unique_ptr<eprosima::fastdds::rtps::FlowController>]’**
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
In file included from /usr/include/c++/5/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/5/bits/char_traits.h:39,
                 from /usr/include/c++/5/ios:40,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iostream:39,
                 from /data/workspace/Fast-DDS/include/fastdds/rtps/common/Time_t.h:24,
                 from /data/workspace/Fast-DDS/include/fastdds/rtps/attributes/WriterAttributes.h:22,
                 from /data/workspace/Fast-DDS/src/cpp/rtps/flowcontrol/FlowControllerFactory.hpp:5,
                 from /data/workspace/Fast-DDS/src/cpp/rtps/flowcontrol/FlowControllerFactory.cpp:1:
/usr/include/c++/5/bits/stl_pair.h:127:17: note: ‘constexpr std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = const std::__cxx11::basic_string<char>; _T2 = std::unique_ptr<eprosima::fastdds::rtps::FlowController>]’ is implicitly deleted because the default definition would be ill-formed:
       constexpr pair(const pair&) = default;
                 ^
**/usr/include/c++/5/bits/stl_pair.h:127:17: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = eprosima::fastdds::rtps::FlowController; _Dp = std::default_delete<eprosima::fastdds::rtps::FlowController>]’**

**Comment by MiguelCompany** [comment]
I think we should use `std::make_pair` [here](https://github.com/eProsima/Fast-DDS/blob/930d7864d12bd7fbed0d31b9a37178ab8be34cc4/src/cpp/rtps/flowcontrol/FlowControllerFactory.cpp#L21-L34).

See [this](https://stackoverflow.com/a/53197779) for a nice explanation

**Comment by MiguelCompany** [comment]
@QinChen686 This should be fixed by #2220. Kindly check on your side.

**Comment by chenzhengxi** [comment]
bug remain in 2.4.1

**Comment by jimlloyd** [comment]
The bug remains in `master`/`2.8.x` as of today (Nov 3, 2022). The problem is that there are 12 locations in `FlowControllerFactory.cpp` that require the change to use `make_pair<>()` but only the first 4 of those locations where changed by #2220.

See all locations where `flow_controllers_.insert` appears.

@MiguelCompany: Should this issue be reopened, or would you prefer a new issue?

**Comment by MiguelCompany** [comment]
@jimlloyd could you check whether #3034 fixes the build issues?

**Comment by jimlloyd** [comment]
@MiguelCompany Yes, #3034 does fix our aarch64 build (gcc 7.2). Thanks!
